version: "3.9"

services:

  db-keepIt:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - .env
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - keepIt-network

  keepit-backend:
      image: backend-keepit-image
      build: ./keepit-backend
      container_name: keepit-backend
      env_file:
        - .env
      environment:
#        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL_POSTGRES_DB}
#        SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#        SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
#        JWT_SECRET: ${JWT_SECRET}
      depends_on:
        db-keepIt:
          condition: service_healthy
      ports:
        - 8080:8080
      networks:
        - keepIt-network


  keepit-frontend:
    build:
      context: ./keepit-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080
    container_name: keepit-frontend
    ports:
      - "80:80"
    networks:
      - keepIt-network
    depends_on:
      - keepit-backend


networks:
  keepIt-network:
    driver: bridge