name: Main — Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push — Backend
        uses: docker/build-push-action@v5
        with:
          context: ./keepit-backend
          push: true
          tags: davimendonca7/keepit-backend:latest

      - name: Build e Push — Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./keepit-frontend
          push: true
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL_PROD }}
          tags: davimendonca7/keepit-frontend:latest

      - name: Deploy no Render
        run: curl -s ${{ secrets.RENDER_DEPLOY_HOOK_URL }}